config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  namespace :admin do
    resources :users
  end

  resources :recipes
  post '/recipes/fetch', to: 'recipes#fetch'
  post '/recipes/reset', to: 'recipes#reset'

  resources :menus, only: [:index, :new, :create]
  get '/menus/edit', to: 'menus#edit'
  get '/menus/select/:id', to: 'menus#select', as: 'select'
  post '/menus/update', to: 'menus#update'
  post '/menus/change_cooked', to: 'menus#change_cooked'
  post '/menus/ready', to: 'menus#ready'
  get '/menus/complete', to: 'menus#complete'
  delete '/menus/destroy', to: 'menus#destroy'

  resources :shopping_lists, only: [:create, :update]
  get '/shopping_lists/show', to: 'shopping_lists#show'
  delete '/shopping_lists/destroy', to: 'shopping_lists#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/menu.rb
class Menu < ApplicationRecord
  before_validation :set_empty_url
  belongs_to :user
  has_one :recipe
  scope :recent, -> { order(schedule: :asc) }

  private

  def set_empty_url
    self.url ||= ''
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :recipes
  has_many :menus
  has_many :shopping_lists
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = current_user.menus.recent

    unless @menus.present?
      redirect_to new_menu_url, notice: "献立表を作成してください。"
    else
      redirect_to menus_edit_path unless current_user.list_readied
    end
    @recipe_ids = @menus.pluck(:recipe_id)
  end

  def select
    @recipes = current_user.recipes.recent
    @menu = current_user.menus.find(params[:id])
    redirect_to menus_edit_path unless @menu.present?
  end

  def new
  end

  def edit
    current_user.update!(list_readied: false) if current_user.list_readied
    @menus = current_user.menus.recent
    @menus.each do |m|
      @readied = m.recipe_id.present?
      break unless @readied
    end
  end

  def create
    result = ExtendMenu.new.list_create(current_user, params[:start_date], params[:end_date])
    redirect_to result[:path], notice: result[:message]
  end

  def update
    message = ExtendMenu.new.list_update(current_user, params[:before_id], params[:after_id])
    redirect_to menus_path, notice: message
  end

  def ready
    readied = params[:readied]
    if readied
      current_user.update!(list_readied: true)
      redirect_to menus_path, notice: "献立表を作成しました。" and return
    end
    redirect_to menus_edit_path, notice: "献立表の作成に失敗しました。" and return
  end

  def complete
    if current_user.list_readied
      result = ExtendMenu.new.list_complete(current_user)
      redirect_to result[:path], notice: result[:message]
    end
  end

  def change_cooked
    menu = current_user.menus.find(params[:menu_id])
    menu.cooked = !menu.cooked
    menu.save
    head :no_content
  end

  def destroy
    menus = current_user.menus.all
    menus.each { |menu| menu.destroy }
    lists = current_user.shopping_lists.all
    lists.each { |list| list.destroy } if lists.present?
    current_user.update!(list_readied: false)
    redirect_to new_menu_url, notice: "献立表を削除しました。"
  end

  private

  def menu_params
    params.require(:menu).permit(:user_id, :recipe_id, :schedule, :name, :url, :cooked)
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/edit.html.slim
h1 献立表編集

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= Menu.human_attribute_name(:schedule)
      th= Menu.human_attribute_name(:name)
      th= Menu.human_attribute_name(:url)
      th
  tbody
    - @menus.each do |menu|
      tr id="menu-#{menu.id}"
        td= menu.schedule
        td= menu.name
        td= link_to menu.url, menu.url
        td
          - edit_btn = menu.recipe_id.present? ? '変更' : '追加'
          - btn_class = menu.recipe_id.present? ? 'btn btn-primary mr-3' : 'btn btn-info mr-3'
          = link_to edit_btn, select_path(menu), class: btn_class

- if @readied
  = link_to '完成', menus_ready_path({ readied: @readied }), method: :post, data: { confirm: '献立表の編集は完了でよろしいですか？' }, class: 'btn btn-success'
= link_to '削除', menus_destroy_path, method: :delete, remote: true, data: { confirm: '献立表を削除します。よろしいですか？' }, class: 'btn btn-danger'

app/views/menus/index.html.slim
h1 献立表

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= Menu.human_attribute_name(:schedule)
      th= Menu.human_attribute_name(:cooked)
      th= Menu.human_attribute_name(:name)
      th= Menu.human_attribute_name(:url)
  tbody
    - @menus.each do |menu|
      tr id="#{menu.id}"
        input id="#{menu.recipe_id}" type="hidden" class="recipe_id"
        td class="schedule"
          = menu.schedule
        td class="menu_cooked"
          = check_box 'menu_cooked', menu.cooked, { checked: menu.cooked }
        td= link_to menu.name, recipe_path(menu.recipe_id)
        td= link_to menu.url, menu.url

= link_to '編集', menus_edit_path, class: 'btn btn-primary'
= link_to '完了', menus_complete_path, data: { confirm: 'レシピ情報を更新し、献立表を削除します。' }, class: 'btn btn-success'
= link_to '買い物リスト作成', shopping_lists_path({ recipe_ids: @recipe_ids }), method: :post, class: 'btn btn-outline-info'

app/views/menus/new.html.slim
h1 献立表作成

p 作成したい期間を選択してください。

= form_with url: menus_path, local: true do |f|
  .form-group.row
    = f.label '開始日'
    .col-auto
      = f.date_field :start_date, class: 'form-control'
    .col-auto
      = f.label '終了日'
    .col-auto
      = f.date_field :end_date, class: 'form-control'
    .col-auto
      = f.submit '作成する', class: 'btn btn-primary'

app/views/menus/select.html.slim
h1 レシピ一覧から選択

p
  - if @menu.name.present?
    h5 変更前
  table  
    tr
      th 日付：
      td= @menu.schedule
    - if @menu.name.present?
      tr
        th 料理名：
        td= @menu.name
    

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= Recipe.human_attribute_name(:cooked)
      th= Recipe.human_attribute_name(:name)
      th= Recipe.human_attribute_name(:url)
      th= Recipe.human_attribute_name(:cooked_at)
      th
  tbody
    - @recipes.each do |recipe|
      tr id="recipe-#{recipe.id}"
        td= recipe.cooked ? '✓' : ''
        td= link_to recipe.name, recipe_path(recipe)
        td= link_to recipe.url, recipe.url
        td= recipe.cooked_at
        td
          = link_to '選択', menus_update_path( params: { before_id: @menu.id, after_id: recipe.id } ), method: :post, class: 'btn btn-primary mr-3'