config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  namespace :admin do
    resources :users
  end

  resources :recipes
  post '/recipes/fetch', to: 'recipes#fetch'
  post '/recipes/reset', to: 'recipes#reset'

  resources :menus, only: [:index, :new, :create]
  get '/menus/edit', to: 'menus#edit'
  get '/menus/select/:id', to: 'menus#select', as: 'select'
  post '/menus/update', to: 'menus#update'
  post '/menus/change_cooked', to: 'menus#change_cooked'
  post '/menus/ready', to: 'menus#ready'
  get '/menus/complete', to: 'menus#complete'
  delete '/menus/destroy', to: 'menus#destroy'

  resources :shopping_lists, only: [:create, :update]
  get '/shopping_lists/show', to: 'shopping_lists#show'
  delete '/shopping_lists/destroy', to: 'shopping_lists#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  attr_accessor :ingredients_attributes
  belongs_to :user
  belongs_to :menu, optional: true
  has_many :ingredients, dependent: :destroy, inverse_of: :recipe
  accepts_nested_attributes_for :ingredients, allow_destroy: true

  validates :name, presence: true

  scope :recent, -> { order(cooked: :asc).order(cooked_at: :asc) }

  def completed(user)
    query = <<-SQL
      SELECT SUM(CASE WHEN recipes.cooked = true THEN 0 ELSE 1 END) AS completed
      FROM recipes
      WHERE user_id = #{user.id}
    SQL

    result = ActiveRecord::Base.connection.select_all(query)
    return result.to_hash[0]["completed"] == 0 ? true : false
  end
  
  def fetch(url)
    fetch_data = FetchRecipe.new(url)
    fetch_data.cookpad
    self.name = fetch_data.title
    self.how_many = fetch_data.how_many
    self.url = fetch_data.url
    self.cooking_recipe = fetch_data.recipe
    self.ingredients_attributes = fetch_data.names.length.times.map { |i| self.ingredients.new( name: fetch_data.names[i], amount: fetch_data.quantitys[i] , quantity: fetch_data.quantitys[i][/\d{1,4}/]) }
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  def index
    @recipes = current_user.recipes.recent
    @completed = Recipe.new.completed(current_user)
  end

  def show
  end

  def new
    @recipe = current_user.recipes.new
    @recipe.ingredients.build
  end

  def edit
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    ingredient_params = params[:recipe][:ingredients_attributes].permit!.to_hash
    @recipe.ingredients_attributes = ingredient_params.map do |key, value|
        @recipe.ingredients.new( name: value['name'], amount: value['amount'], quantity: value['quantity'], unit_id: value['unit_id'].to_i )
      end

    if @recipe.save
       redirect_to @recipe, notice: "レシピ「#{@recipe.name}」を登録しました。"
    else
      render :new
    end
  end

  def fetch
    @recipe = current_user.recipes.new
    @recipe.fetch(params[:fetch_url])
    
    if params[:new].present?
      render :new
    elsif params[:edit].present?
      render :edit
    end
  end

  def reset
    completed = params[:completed]
    if completed
      recipes = current_user.recipes.all
      recipes.each { |recipe| recipe.update!(cooked: false) }
      redirect_to recipes_path, notice: "レシピリストをリセットしました。"
    end
  end

  def update
    recipe = current_user.recipes.find(params[:id])
    recipe.update!(recipe_params)
    redirect_to recipes_path, notice: "レシピ「#{recipe.name}」を更新しました。"
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path, notice: "レシピ「#{@recipe.name}」を削除しました。"
  end

  private

  def recipe_params
    params.require(:recipe).permit( :cooked, :name, :url, :cooking_recipe, :cooked_at, :how_many, ingredients_attributes: [ :name, :amount, :quantity, :unit_id ] )
  end

  def set_recipe
    @recipe = current_user.recipes.find(params[:id])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.slim
= form_with model: recipe, local: true do |f|
  .form-group.row
    = f.label :name, class: 'col-sm-1 col-form-label'
    .col-sm-6
      = f.text_field :name, value: recipe.name, class: 'form-control'
  .form-group.row
    = f.label :url, class: 'col-sm-1 col-form-label'
    .col-sm-6
      = f.text_field :url, value: recipe.url, class: 'form-control'
  .form-group.row
    = f.label :cooking_recipe, class: 'col-sm-1 col-form-label'
    .col-sm-8
      = f.text_area :cooking_recipe, value: recipe.cooking_recipe, rows: "10", class: 'form-control', id: 'cooking_recipe'
  = f.fields_for :ingredients do |i|
    .form-group.row
      = i.label :name, class: 'col-form-label'
      .col-sm-3
        = i.text_field :name, value: i.object.name, class: 'form-control'
      = i.label :amount, class: 'col-form-label'
      .col-sm-2
        = i.text_field :amount, value: i.object.amount, class: 'form-control'
      = i.label :quantity, class: 'col-form-label'
      .col-sm-2
        = i.text_field :quantity, class: 'form-control'
      = i.label :unit_id, class: 'col-form-label'
      .col-sm-2
        = i.select :unit_id, Ingredient.unit_ids.map {|key, value| [I18n.t("enums.ingredient.unit_id.#{key}"), value]}
  - if recipe.id.present?
    br
    .form-check
      = f.label :cooked, class: 'form-check-label' do
        = f.check_box :cooked, class: 'form-check-input'
        | 調理済み
    br
  = f.submit nil, class: 'btn btn-primary'

app/views/recipes/edit.html.slim
h1 レシピの編集

.nav.justify-content-end
  = link_to 'レシピ一覧', recipes_path, class: 'nav-link'

- if @recipe.errors.present?
  ul#error_explanation
  - @recipe.errors.full_messages.each do |message|
    li= message
p.mb-3
  = form_with url: recipes_fetch_path, local: true do |f|
    p 取り込みたいレシピのURLを入力してください
    .form-group.row
      = f.label '取込URL', class: 'col-sm-1 col-form-label'
      .col-sm-5
        = f.text_field :fetch_url, class: 'form-control'
      .col-sm-2
        = f.submit '取込', name: 'edit', class: 'btn btn-primary'

= form_with model: @recipe, local: true do |f|
  .form-group.form-check.row
    .col-sm-6
      = f.label :cooked, class: 'form-check-label' do
        = f.check_box :cooked, class: 'form-check-input'
        | 調理済み
  .form-group.row
    .col-sm-2
      = f.label :cooked_at, class: 'col-form-label'
    .col-sm-5
      = f.date_field :cooked_at, value: @recipe.cooked_at, class: 'form-control'
  .form-group.row
    .col-sm-1
      = f.label :name, class: 'col-form-label'
    .col-sm-6
      = f.text_field :name, value: @recipe.name, class: 'form-control'
  .form-group.row
    .col-sm-1
      = f.label :url, class: 'col-form-label'
    .col-sm-6
      = f.text_field :url, value: @recipe.url, class: 'form-control'
  .form-group.row.mb-3
    .col-sm-1
      = f.label :how_many, class: 'col-form-label'
    .col-sm-6
      = f.text_field :how_many, value: @recipe.how_many, class: 'form-control'
  br
    .row
    label.mr-3.mt-2 もとの分量
    input#original.col-sm-1.quantity type="number" min="1"
    label.mr-5.mt-2  人分
    label.mr-3.mt-2  登録する分量
    input#register.col-sm-1.quantity type="number" min="1"
    label.mr-5.mt-2  人分
    button#conversion.btn.btn-info type="button" 変換
  br
    table#ing_table.table
        thead
          tr.form-group.row
            th.col-sm-2= Ingredient.human_attribute_name(:name)
            th.col-sm-2= Ingredient.human_attribute_name(:amount)
            th.col-sm-2= Ingredient.human_attribute_name(:quantity)
            th.col-sm-2= Ingredient.human_attribute_name(:unit_id)
            th.button.btn.btn-info.col-sm-1 id="addRow" 行追加
        tbody
          = f.fields_for :ingredients do |i|
            tr.form-group.row
              td.col-sm-2= i.text_field :name, value: i.object.name, class: 'form-control'
              td.col-sm-2= i.text_field :amount, value: i.object.amount, class: 'form-control'
              td.col-sm-2= i.text_field :quantity, class: 'form-control mod-quantity'
              td.col-sm-2= i.select :unit_id, Ingredient.unit_ids.map {|key, value| [I18n.t("enums.ingredient.unit_id.#{key}"), value]}
              td.col-sm-1
                button.remove -
  br
  .form-group.row
    .col-sm-1
      = f.label :cooking_recipe, class: 'col-form-label'
    .col-sm-8
      = f.text_area :cooking_recipe, value: @recipe.cooking_recipe, rows: "10", class: 'form-control', id: 'cooking_recipe'
  br
  = f.submit nil, class: 'btn btn-primary'
  /button.btn.btn-info id="addRow" 行追加

app/views/recipes/index.html.slim
h1 レシピ一覧

tr
  - if @completed
    .alert.alert-success 
      レシピリストをコンプリートしました。リストをリセットしてください。
    = link_to 'リセット', recipes_reset_path({completed: @completed}), method: :post, class: 'btn btn-info mr-3'
  = link_to '新規登録', new_recipe_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= Recipe.human_attribute_name(:cooked)
      th= Recipe.human_attribute_name(:name)
      th= Recipe.human_attribute_name(:url)
      th= Recipe.human_attribute_name(:cooked_at)
      th
  tbody
    - @recipes.each do |recipe|
      tr id="recipe-#{recipe.id}"
        td= recipe.cooked ? '✓' : ''
        td= link_to recipe.name, recipe_path(recipe)
        td= link_to recipe.url, recipe.url
        td= recipe.cooked_at
        td
          = link_to '編集', edit_recipe_path(recipe), class: 'btn btn-primary mr-3'
          = link_to '削除', recipe, method: :delete, remote: true, data: { confirm: "レシピ「#{recipe.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'

app/views/recipes/new.html.slim
h1 レシピの新規登録

.nav.justify-content-end
  = link_to 'レシピ一覧', recipes_path, class: 'nav-link'

- if @recipe.errors.present?
  ul#error_explanation
    - @recipe.errors.full_messages.each do |message|
      li= message

= form_with url: recipes_fetch_path, local: true do |f|
  p 取り込みたいレシピのURLを入力してください
  .form-group.row
    .col-sm-1
      = f.label '取込URL', class: 'col-form-label'
    .col-sm-5
      = f.text_field :fetch_url, class: 'form-control'
    .col-sm-2
      = f.submit '取込', name: 'new', class: 'btn btn-primary'
br
br
= form_with model: @recipe, local: true do |f|
  .form-group.row
    .col-sm-1
      = f.label :name, class: 'col-form-label'
    .col-sm-6
      = f.text_field :name, value: @recipe.name, class: 'form-control'
  .form-group.row
    .col-sm-1
      = f.label :url, class: 'col-form-label'
    .col-sm-6
      = f.text_field :url, value: @recipe.url, class: 'form-control'
  .form-group.row
    .col-sm-1
      = f.label :how_many, class: 'col-form-label'
    .col-sm-6
      = f.text_field :how_many, value: @recipe.how_many, class: 'form-control'
  br
  .row
    label.mr-3.mt-2 もとの分量
    input#original.col-sm-1.quantity type="number" min="1"
    label.mr-5.mt-2  人分
    label.mr-3.mt-2  登録する分量
    input#register.col-sm-1.quantity type="number" min="1"
    label.mr-5.mt-2  人分
    button#conversion.btn.btn-info type="button" 変換
  br
    table#ing_table.table
      thead
        tr.form-group.row
          th.col-sm-2= Ingredient.human_attribute_name(:name)
          th.col-sm-2= Ingredient.human_attribute_name(:amount)
          th.col-sm-2= Ingredient.human_attribute_name(:quantity)
          th.col-sm-2= Ingredient.human_attribute_name(:unit_id)
          th.button.btn.btn-info.col-sm-1 id="addRow" 行追加
      tbody
        = f.fields_for :ingredients do |i|
          tr.form-group.row
            td.col-sm-2= i.text_field :name, value: i.object.name, class: 'form-control'
            td.col-sm-2= i.text_field :amount, value: i.object.amount, class: 'form-control'
            td.col-sm-2= i.text_field :quantity, value: i.object.quantity, class: 'form-control mod-quantity'
            td.col-sm-2= i.select :unit_id, Ingredient.unit_ids.map {|key, value| [I18n.t("enums.ingredient.unit_id.#{key}"), value]}
            td.col-sm-1
              button.remove -
  .form-group.row
    .col-sm-1
      = f.label :cooking_recipe, class: 'col-form-label'
    .col-sm-8
      = f.text_area :cooking_recipe, value: @recipe.cooking_recipe, rows: "10", class: 'form-control', id: 'cooking_recipe'
  br
  = f.submit nil, class: 'btn btn-primary'

app/views/recipes/show.html.slim
h1 レシピの詳細

.nav.justify-content-end
  = link_to 'レシピ一覧', recipes_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th.col-sm-1= Recipe.human_attribute_name(:cooked)
      td.col-sm-3= @recipe.cooked ? '✓' : ''
    tr
      th= Recipe.human_attribute_name(:name)
      td= @recipe.name
    tr
      th= Recipe.human_attribute_name(:url)
      td= link_to @recipe.url, @recipe.url
    tr
      th= Recipe.human_attribute_name(:cooking_recipe)
      td= simple_format(h(@recipe.cooking_recipe), {}, sanitize: false, wrapper_tag: "div")
    tr
      th= Recipe.human_attribute_name(:cooked_at)
      td= @recipe.cooked_at      
br
table.table.table-hover
  tbody
    tr
      th.col-sm-1= Ingredient.human_attribute_name(:name)
      th.col-sm-3= Ingredient.human_attribute_name(:amount) + @recipe.how_many.to_s
    - @recipe.ingredients.each do |i|
      tr
        td= i.name
        td= i.amount

= link_to '編集', edit_recipe_path, class: 'btn btn-primary mr-3'
= link_to '削除', @recipe, method: :delete, data: { confirm: "レシピ「#{@recipe.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'