config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  namespace :admin do
    resources :users
  end

  resources :recipes
  post '/recipes/fetch', to: 'recipes#fetch'
  post '/recipes/reset', to: 'recipes#reset'

  resources :menus, only: [:index, :new, :create]
  get '/menus/edit', to: 'menus#edit'
  get '/menus/select/:id', to: 'menus#select', as: 'select'
  post '/menus/update', to: 'menus#update'
  post '/menus/change_cooked', to: 'menus#change_cooked'
  post '/menus/ready', to: 'menus#ready'
  get '/menus/complete', to: 'menus#complete'
  delete '/menus/destroy', to: 'menus#destroy'

  resources :shopping_lists, only: [:create, :update]
  get '/shopping_lists/show', to: 'shopping_lists#show'
  delete '/shopping_lists/destroy', to: 'shopping_lists#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Kondate
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand KondateApp
      ul.navbar-nav.ml-auto
        - if current_user
          li.nav-item= link_to '献立表', menus_path, class: 'nav-link'
          li.nav-item= link_to '買い物リスト', shopping_lists_show_path, class: 'nav-link'
          li.nav-item= link_to 'レシピ一覧', recipes_path, class: 'nav-link'
          - if current_user.admin?
            li.nav-item= link_to 'ユーザー一覧', admin_users_path, class: 'nav-link'
          li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
    .container
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      = yield